name: Java CI with Ant

on:
  push:
    branches: [ "main" ]   # Runs whenever you push to main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Ant
        run: |
          ant clean
          ant compile
          ant jar
          ant run

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: StudentManagementSystem
          path: dist/StudentManagementSystem.jar
